---
- name: Provision all OpenStack instances
  hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tags:
    - database_servers
    - application_servers
    - load_balancers

  roles:
    - os_server

  tasks:
    - name: Gather OpenStack server details
      openstack.cloud.server_info:
        # cloud: "{{ guid }}-project" # Comment out if using Tower
      register: os_instances

    - name: Add OpenStack instances to in-memory inventory
      add_host:
        name: "{{ item.name }}"
        group: "{{ item.metadata.AnsibleGroup }}"
        ansible_host: "{{ item.private_v4 }}" 
      when: item.metadata.AnsibleGroup is defined
      loop: "{{ os_instances.openstack_servers }}"
      loop_control:
        label: "{{ item.name }}"
