---
- name: Play to provision OpenStack servers
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - os_server

  tasks:
    - name: Gather OpenStack server details
      os_server_info:
        cloud: "{{ guid }}-project"
      register: os_instances

    - name: Add OpenStack instances to in-memory inventory
      add_host:
        name: "{{ item.name }}"
        group: osp_instances
        ansible_host: "{{ item.private_v4 }}" 
      when: item.metadata.AnsibleGroup == "osp_instances"
      loop: "{{ os_instances.openstack_servers }}"

- name: Play to configure OpenStack servers
  hosts: osp_instances
  connection: local
  gather_facts: no

  roles:
    - register_satellite
        